<?php
/* @var \Magento\Catalog\Block\Category\View $block */
$currentCategory = $block->getCurrentCategory();
//to fetch subcategories
$subcategories = $currentCategory->getChildrenCategories();
if ($subcategories->count() > 0) {
    echo '<ul>';
    foreach ($subcategories as $subcategory) {
        echo '<li><a href="' . $subcategory->getUrl() . '">' . $subcategory->getName() . '</a></li>';
    }
    echo '</ul>';
} else {
    echo $block->getProductListHtml();
}
?>
